### ISSUE TITLE
Tags for versions

### ISSUE THREAD

**Issue by dlangerenken** [stomp-js/stomp-websocket#13]
Hi,
it seems like you haven't created tags for the versions 3.0.2 and 3.0.3. I find these versions on NPM. Could you create these missing tags please? 

Thanks

**Comment by kum-deepak** [comment]
Pushed these tags :)

**Comment by kum-deepak** [comment]
The master branch has moved since 3.0.3, functionally still the same, but documentation and test cases have been refactored heavily. This will get released as 3.1.0.

If you want to make changes, I will suggest you pick this version as base, you are likely to find it easier.

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1
