### ISSUE TITLE
Reconnect fires only once

### ISSUE THREAD

**Issue by lifecoderua** [stomp-js/stomp-websocket#15]
Maybe I miss something but it looks like only one reconnect attempt is made. If it fails (server unavailable, etc.) setTimeout is fired and then client just waits forever. Any good way to work around this?

**Comment by kum-deepak** [comment]
This is tested with RabbitMQ, where it does not seem to have that problem. Which server are you using?

**Comment by lifecoderua** [comment]
I'm using STOMP over SockJS, this issue occure if the server is down,

**Comment by kum-deepak** [comment]
Before I proceed with more suggestions - are you using the SockJS as suggested in https://stomp-js.github.io/stomp-websocket/codo/extra/docs-src/sockjs.md.html 

Key is to pass a function that returns a SockJS object (so that before each connect/reconnect it can create a new SockJS instance).

In any case, please fork and submit a pull request. https://stomp-js.github.io/stomp-websocket/codo/extra/docs-src/Contribute.md.html may help you in getting started.

**Comment by ermannos** [comment]
I had the same issue, after the first disconnection the client was stuck with the message 'Opening Web Socket...'.
After changing my code following kum-deepak suggestions everything work fine, the stomp client continues to try to reconnect.

**Comment by lifecoderua** [comment]
Hm, function may be a way. I have a code from the original stomp-websocket, which works over a single object, which should be the reason.
I've end up with a reconnecting-websocket library, connected to a SockJS plain websocket server (/<endpoint>/websocket), which works just as good.

Thank you for the support!

**Comment by zkendall** [comment]
I am also having this problem. But I am not using SockJS. Why should reconnect depend on SockJS or the method the connection is created?

I've tried both:
`this.stomp = Stomp.over(() => { return new WebSocket(endpoint) });`
`this.stomp = Stomp.client(endpoint);`

Both yield output like this:

> "2018-01-17T21:21:54.021Z" - Opening Web Socket...
> 
> "2018-01-17T21:21:54.050Z" - Web Socket Opened...
> 
> "2018-01-17T21:21:54.050Z" - >>> CONNECT accept-version:1.2,1.1,1.0 heart-beat:10000,10000 
> 
> "2018-01-17T21:21:54.063Z" - <<< CONNECTED session:session-JYMByDAr1iTEZxtXuhiJgg heart-beat:10000,10000 server:RabbitMQ/3.4.1 version:1.2 user-name:testuser 
> 
> "2018-01-17T21:21:54.063Z" - connected to server RabbitMQ/3.4.1
> 
> "2018-01-17T21:21:54.063Z" - send PING every 10000ms
> 
> "2018-01-17T21:21:54.063Z" - check PONG every 10000ms
> 
> "2018-01-17T21:22:03.964Z" - <<< PONG
> 
> "2018-01-17T21:22:04.064Z" - >>> PING
> 
> "2018-01-17T21:22:13.865Z" - <<< PONG
> 
> "2018-01-17T21:22:14.066Z" - >>> PING
> 
> {{ I RESTART MY WS SERVER }}
> 
> "2018-01-17T21:22:29.026Z" - Whoops! Lost connection to ws://localhost:8089/websocket-ui-service/ws?TOKEN=abc
> 
> "2018-01-17T21:22:29.026Z" - Whoops! Lost connection to ws://localhost:8089/websocket-ui-service/ws?TOKEN=abc

I'm not sure why there is a double "Lost connection". Is that part of the retry?

**Comment by kum-deepak** [comment]
Good to know.

A simple explanation of why reconnect might behave differently: SockJS and WebSocket are two different protocols. Internally SockJS has multiple variants for actual underlying connectivity. This make catching the disconnect event to behave differently. In some of the SockJS connectivity variants it may be a while before this library will know about the disconnection. Once this library knows that it has disconnected the reconnect process is same.
