### ISSUE TITLE
Exception when debug function is not defined

### ISSUE THREAD

**Issue by aalbericio** [stomp-js/stomp-websocket#20]
If you use this library setting debug=null (I don't want a debug function at all), reconnections will throw an Exception and your application may become unstable:

Line:
@debug("STOMP: scheduling reconnection in #{@reconnect_delay}ms")

Should become something like:
@debug?("STOMP: scheduling reconnection in #{@reconnect_delay}ms")

This bug also affects the JS and minified version, of course.

If you could, please, fix it. 

Thanks for your dedication and work.

**Comment by kum-deepak** [comment]
Will fix it, need few days.

**Comment by kum-deepak** [comment]
Released version 4.0.1, please check if the issue is fixed.

**Comment by aalbericio** [comment]
How do you want me to check that? npm install stompjs@4.0.1 is not released...

**Comment by aalbericio** [comment]
Verified. 

I installed the 4.0.1 tag version and pointed to that version in our package.json file. 

The Exception is gone.

Thanks

**Comment by kum-deepak** [comment]
Thanks, will close the issue.

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1
