### ISSUE TITLE
4.2.0 is not available on bower

### ISSUE THREAD

**Issue by Anikethana** [stomp-js/stomp-websocket#26]
Can you guys update bower, with latest version 4.2.0

**Comment by kum-deepak** [comment]
Added this project as `stompjs` in bower. Try the following:

```bash
$ bower install stompjs
```

Latest version is 4.0.2

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1
