### ISSUE TITLE
NodeJS Legacy link on description 404

### ISSUE THREAD

**Issue by Textras** [stomp-js/stomp-websocket#27]
Just a heads up the NodeJS Legacy link under description is throwing a 404.
------
"If you are using this library in NodeJS you should definitely check NodeJS Legacy."

https://stomp-js.github.io/stomp-websocket/codo/extra/docs-src/nodejs.md.html

**Comment by kum-deepak** [comment]
Pushed a commit with documentation changes, please see if it is consistent now.

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1
