### ISSUE TITLE
Integrate improvements from firestar fork

### ISSUE THREAD

**Issue by derekm** [stomp-js/stomp-websocket#28]
firestar's fork has some valuable improvements that may still be relevant to this fork:
https://github.com/firestar/stomp-websocket

**Comment by kum-deepak** [comment]
Thanks! Let me have a look.

**Comment by kum-deepak** [comment]
Create pull request #29, to move this task. It will need updates in documentation and test cases.

**Comment by kum-deepak** [comment]
Any help will be highly appreciated.

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1

**Comment by kum-deepak** [comment]
This and more added into v5.0.0. Please upgrade https://stomp-js.github.io/stompjs/additional-documentation/upgrading.html
