### ISSUE TITLE
Is there a way to increase the client's maxWebSocketFrameSize?

### ISSUE THREAD

**Issue by ealexhaywood** [stomp-js/stomp-websocket#32]
Is there a way to increase the client's maxWebSocketFrameSize?

Our server can handle larger messages, and the stomp client is unable to send some of our messages.  As an aside, this was difficult for me to debug because no error message is thrown by stomp-js ... My larger messages were just dropped mysteriously.

Thanks.

**Comment by kum-deepak** [comment]
I will have a look. Meanwhile which server you are using? What size of messages you are trying to send?

**Comment by ealexhaywood** [comment]
Thanks!  We're using ActiveMQ on the backend.  These messages are greater than 16kb but less than 50kb.  About 1000-2000 line json messages.

**Comment by kum-deepak** [comment]
Ok, I will check.

**Comment by ealexhaywood** [comment]
I was actually able to define it myself by directly accessing the Client's properties like so:

```
    this.client = Stomp.client(this.props.url);
    this.client.maxWebSocketFrameSize = 128 * 1024; // 128kb
```

Everything works :)

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1

**Comment by jmls** [comment]
I am having the same problem, but can't seem to fix it right .. I have set 
`this.client.maxWebSocketFrameSize = 128 * 1024 * 2048;` - which makes it ` maxWebSocketFrameSize: 268435456,`

yet when I send a large (1.2MB) message I get this crash

`reason: 'Frame size of 1233300 bytes exceeds maximum accepted frame size',`

anyone got any clue ?

**Comment by wazirsoft** [comment]
@jmls do you have these two parameters added to `transportConnector` in **activemq.xml** file?

wireFormat.maxFrameSize=104857600
websocket.maxTextMessageSize=999999 

like this 
```
<transportConnectors>
    <transportConnector name="ws" uri="ws://0.0.0.0:61614?maximumConnections=1000&amp;wireFormat.maxFrameSize=104857600&amp;websocket.maxTextMessageSize=999999"/>
</transportConnectors>

**Comment by jmls** [comment]
I'm not running activemq , but will look at the rabbitmq options ;) thanks
