### ISSUE TITLE
closeEventCallback doesn't work with both connect signatures.

### ISSUE THREAD

**Issue by zkendall** [stomp-js/stomp-websocket#35]
Documentation says that these should both work.
> client.connect(headers, connectCallback, errorCallback, closeEventCallback);
> client.connect(login, passcode, connectCallback, errorCallback, closeEventCallback);

However, in my code ONLY the SECOND one works.

So I converted:
> _stomp.connect({}, connectCallback, errCallback, closeEventCallback);

to this:
> _stomp.connect('', '', connectCallback, errCallback, closeEventCallback);

I determined this is what it was trying to do because with the first version, the closeEventCallback was being called with the error message typically sent to errCallback.

**Comment by kum-deepak** [comment]
I do realize it is a mess with so many alternate syntax. I am planning to make a non backward compatible change where all options are set and then connect is called without any parameters.

**Comment by zkendall** [comment]
Roger. Thanks.
