### ISSUE TITLE
Get Handshake Response code / Don't retry on 403

### ISSUE THREAD

**Issue by zkendall** [stomp-js/stomp-websocket#36]
I'm tearing my hair out trying to not retry on 403 response code from initial handshake.

![screen shot 2018-05-11 at 12 34 39 pm](https://user-images.githubusercontent.com/2762875/39944014-c9fff18c-5519-11e8-80eb-e5ecfac382bd.png)

Do you know of any way to do this or can it be added to feature backlog?

**Comment by kum-deepak** [comment]
It has been a black box for me as well. There is WebSocket handshake which happens at the time of opening WebSocket connection. The actual requests are opaque and I have not been able to find a way to access those.

The Exception that you are seeing is within libraries Browser maintains - definitely likely to vary across Browsers.

**Comment by kum-deepak** [comment]
Closing this issue, please reopen if needed.

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1
