### ISSUE TITLE
reconnect_delay missing from types

### ISSUE THREAD

**Issue by jmls** [stomp-js/stomp-websocket#42]
Looks like the `reconnect_delay` option is not present in the @types/stompjs

**Comment by kum-deepak** [comment]
Not sure if this helps, please check https://github.com/stomp-js/stomp-websocket/blob/master/index.d.ts#L21

**Comment by kum-deepak** [comment]
By the way, are you trying to use types from definitely typed?

This project distributes types as part of the npm package, which is kept up to date.
