### ISSUE TITLE
npm version and github version not same

### ISSUE THREAD

**Issue by Lexanius** [stomp-js/stomp-websocket#8]
Npm has the version 2.5.4 and in github is version 3.0.0 released

**Comment by kum-deepak** [comment]
Thanks for pointing out. It was a forked repository, had not realized it already had version tagged at 3.0. The new version I have released now is 3.0.1 both at npm and GitHub.

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1
