### ISSUE TITLE
Support for protobuf

### ISSUE THREAD

**Issue by pantonis** [stomp-js/stomp-websocket#9]
As web is evolving protobuf is being used more and more due to its serialization speed and the small payload size compared to JSON.

Can you develop support for protobuf?

**Comment by kum-deepak** [comment]
This will indeed be a good feature. Unfortunately I will not be able to take it up right now. If you are able to get it working please raise a PR. Many thanks!

**Comment by pantonis** [comment]
kum-deepak can you give me your skype or email?

**Comment by kum-deepak** [comment]
Not active on Skype. My email is deepak@kreatio.com

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1

Support for binary payloads (needed to fix this) will get attempted 😄

**Comment by pantonis** [comment]
@kum-deepak any news on this one? wish I had the knowledge to help

**Comment by kum-deepak** [comment]
The work is actually more involved than it sounds. The current parser relies on strings - as it uses Javascript Regular expressions. The binary bodies are likely to get messed up while converting to String. Also the current parser fails if the body has NULL octate.

The solution I have been thinking is to write a parser that works directly on octates and converts only specific parts to strings (command and headers).

I have been working on this parser - please check https://github.com/stomp-js/stompjs/pull/6

**Comment by pantonis** [comment]
I will check it in weekend as I am overloaded right now !

Thanks

**Comment by kum-deepak** [comment]
Changes have been merged into master. I have tested round trip of binary payload. https://github.com/stomp-js/stompjs/blob/master/spec/unit/compatibility/message.spec.js#L28

**Comment by kum-deepak** [comment]
Added in v5.0.0. Please upgrade https://stomp-js.github.io/stompjs/additional-documentation/upgrading.html
